# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    google:
        enabled: true                  # If Google Authenticator should be enabled, default false
        server_name: 2fa       # Server name used in QR code
        issuer: My 2fa test app            # Issuer name used in QR code
        digits: 6                      # Number of digits in authentication code
        leeway: 15                      # Acceptable time drift in seconds, must be less or equal than 30 seconds
