framework:
    messenger:
        transports:
            sync: 'sync://'
        routing:
            # force email to be sent synchronously in dev env
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
